### ISSUE TITLE
CDMI API doesn't work?

### ISSUE THREAD

**Issue by MrCreosote** [kbase/nextgen#9]
https://github.com/kbase/nextgen/blame/master/docs/challenges/data.md#L17

What does this mean?

**Comment by dangunter** [comment]
@mlhenderson can provide details, but perhaps it helps to say that it doesn't work for our purposes.

**Comment by mlhenderson** [comment]
I had a good amount of experience using the cdmi_api, and we (Search)
attempted to use it for extracting all the genome and feature data out of
the central store for indexing purposes. Dumping the tables turned out to
be a more reliable and practical option.  Future data apis and
implementations need to work more effectively for accessing large genomes
in particular.  I would not say that the cdmi failed to work period.

**Comment by dangunter** [comment]
I have moved this issue to JIRA

https://atlassian.kbase.us/browse/NEXTGEN-13
